services:
  code-server:
    build: .
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - ./html:/home/dev/html
      - ./slides:/home/dev/slides
      - ./.config/config.yaml:/home/dev/.config/code-server/config.yaml
      - ./data/extensions:/home/dev/.local/share/code-server/extensions
